config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index' => 'home#index'

  devise_for :students, controllers: {
    sessions:       'students/sessions',
    passwords:      'students/passwords',
    registrations:  'students/registrations'
  }
  resources :students, only: [:index, :show]
  # get 'students/index' => 'students#index'
  # get 'students/show' => 'students#show'


  devise_for :teachers, controllers: {
    sessions:       'teachers/sessions',
    passwords:      'teachers/passwords',
    registrations:  'teachers/registrations'
  }
  resources :teachers, only: [:index, :show]
  # get 'teachers/index' => 'teachers#index'
  # get 'teachers/show' => 'teachers#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :student_followings, only: [:show, :create, :destroy]
  resources :teacher_followings, only: [:show, :create, :destroy]

  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create]
  end


end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :student_followings, foreign_key: 'follow_id', dependent: :destroy
  has_many :teacher_followings, foreign_key: 'followed_id', dependent: :destroy
  has_many :followings, through: :student_followings, source: :followed
  has_many :followers, through: :teacher_followings, source: :follow
  has_many :rooms

  mount_uploader :icon, IconUploader

  def follow(teacher)
    self.student_followings.find_or_create_by(followed_id: teacher.id)
  end

  def unfollow(teacher)
    relationship = self.student_followings.find_by(followed_id: teacher.id)
    relationship.destroy if relationship
  end

  def already_following?(teacher)
    self.followings.include?(teacher)
  end

  def already_followed?(teacher)
    self.followers.include?(teacher)
  end

end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_sign_up_path_for(resource)
    students_path(resource)
  end

  def after_update_path_for(resource)
    student_path(resource)
  end

end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    students_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :authenticate_student!, except: [:show]

  def index
    @student = current_student
    if params[:search] == nil
      @teachers = Teacher.all
    elsif params[:search] == ""
      @teachers = Teacher.all
    else
      split_keyword = params[:search].split(/[[:blank:]]+/)
      @teachers = []
      split_keyword.each do |sk|
        next if sk == ""
        @teachers += Teacher.where('name like(?) or profile like(?) or subject like(?)', "%#{sk}%","%#{sk}%","%#{sk}%")
      end
      @teachers.uniq!
    end
  end

  def show
    @student = Student.find(params[:id])
    if teacher_signed_in?
      rooms = current_teacher.rooms
      @student_ids = []
      rooms.each do |r|
        @student_ids << r.student_id
      end
      @following = current_teacher.already_following?(@student)
      @followed = current_teacher.already_followed?(@student)
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_nav.html.erb
  <nav>
    <div class="my-info">
      <%= link_to student_path(current_student.id) do %>
        <%= user_icon(current_student) %>
      <% end %>
      <div class="name">
        <%= current_student.name %>
      </div>
      <div class="detail">
        <div class="profile"><span>プロフィール：</span><%= current_student.profile %></div>
      </div>
    </div>
    <ul class="gnavi">
      <li><%= link_to 'ホーム', root_path %></li>
      <li><%= link_to 'プロフィール', student_path(current_student.id) %></li>
      <li><%= link_to 'マッチング画面', students_path %></li>
      <li><%= link_to 'ログアウト', destroy_student_session_path, method: :delete %></li>
    </ul>
    <div class="side-footer">
      Copyright <br>
      &copy; Tsuyoshi Nakayama <br>
      All Rights Reserved.
    </div>
  </nav>

app/views/students/index.html.erb
<div class="students-index">
  <%= navigation_bar %>

  <main>
    <div class="search-form">
      <%= form_tag({controller:"students",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索'  %>
      <% end %>
    </div>
    <h3>先生一覧</h3>
    <div class="users">
      <% @teachers.each do |t| %>
        <hr>
        <div class="user">
          <%= link_to teacher_path(t.id) do %>
            <div class="user-icon"><%= user_icon(t) %></div>
            <div class="info">
              <div class="name"><%= t.name %></div>
              <div class="subject"><span>担当科目：</span><%= t.subject %></div>
              <div class="profile"><span>プロフィール：</span><%= t.profile %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </main>
</div>

app/views/students/show.html.erb
<div class="students-show">
  <%= navigation_bar %>

  <main>
    <div class="icon-button">
      <%= user_icon(@student) %>
      <% if student_signed_in? %>
        <div class="buttons">
          <%= link_to '編集', edit_student_registration_path, class: 'button' %>
          <%= link_to 'フォロー/フォロワー', student_following_path(@student.id), class: 'button' %>
        </div>
      <% elsif teacher_signed_in? %>
        <%= render 'teacher_followings/follow_button', student: @student %>
        <%= render 'teacher_followings/DM_link', stu: @student, ids: @student_ids, flwng: @following, flwd: @followed %>
      <% else %>
        ※ログインしてください。
      <% end %>
    </div>
    <div class="name"><span>名前：</span><%= @student.name %></div>
    <div class="profile"><span>プロフィール：<br></span><%= @student.profile %></div>
  </main>
</div>