config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index' => 'home#index'

  devise_for :students, controllers: {
    sessions:       'students/sessions',
    passwords:      'students/passwords',
    registrations:  'students/registrations'
  }
  resources :students, only: [:index, :show]
  # get 'students/index' => 'students#index'
  # get 'students/show' => 'students#show'


  devise_for :teachers, controllers: {
    sessions:       'teachers/sessions',
    passwords:      'teachers/passwords',
    registrations:  'teachers/registrations'
  }
  resources :teachers, only: [:index, :show]
  # get 'teachers/index' => 'teachers#index'
  # get 'teachers/show' => 'teachers#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :student_followings, only: [:show, :create, :destroy]
  resources :teacher_followings, only: [:show, :create, :destroy]

  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create]
  end


end

app/models/student_following.rb
class StudentFollowing < ApplicationRecord
  belongs_to :follow, class_name: 'Student'
  belongs_to :followed, class_name: 'Teacher'

  validates :follow_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/student_followings_controller.rb
class StudentFollowingsController < ApplicationController

  before_action :authenticate_student!, except: [:show]

  def show
    @teachers = Teacher.all
    rooms = current_student.rooms
    @teacher_ids = []
    rooms.each do |r|
      @teacher_ids << r.teacher_id
    end
  end

  def create
    @teacher = Teacher.find(params[:followed_id])
    following = current_student.follow(@teacher)
    if following.save
      flash[:success] = '先生をフォローしました'
      redirect_to @teacher
    else
      flash.now[:alert] = '先生のフォローに失敗しました'
      redirect_to @teacher
    end
  end

  def destroy
    @teacher = Teacher.find(params[:followed_id])
    following = current_student.unfollow(@teacher)
    if following.destroy
      flash[:success] = '先生のフォローを解除しました'
      redirect_to @teacher
    else
      flash.now[:alert] = '先生のフォロー解除に失敗しました'
      redirect_to @teacher
    end
  end

  private

end

app/helpers/student_followings_helper.rb
module StudentFollowingsHelper
end

app/views/student_followings/_DM_link.html.erb
  <% if flwng && flwd %>
    <% if ids.include?(tea.id) %>
      <%= link_to 'DMへ', room_path(current_student.rooms.find_by(teacher_id: tea.id)), class: 'button' %>
    <% else %>
      <%= form_for Room.new do |f| %>
        <%= f.hidden_field :teacher_id, :value => tea.id %>
        <%= f.submit "ルーム作成", class: 'button' %>
      <% end %>
    <% end %>
  <% elsif flwd %>
    <div class="comment">フォローしてください</div>
  <% elsif flwng %>
    <div class="comment">フォローされていません</div>
  <% else %>
    <div class="comment">DMを送るためには相互フォローである必要があります</div>
  <% end %>

app/views/student_followings/_follow_button.html.erb
<% if current_student.already_following?(teacher) %>
  <%= form_for(current_student.student_followings.find_by(followed_id: teacher.id), method: :delete) do |f| %>
    <%= hidden_field_tag :followed_id, teacher.id %>
    <%= f.submit 'Unfollow', class: 'button' %>
  <% end %>
<% else %>
  <%= form_for(current_student.student_followings.build) do |f| %>
    <%= hidden_field_tag :followed_id, teacher.id %>
    <%= f.submit 'Follow', class: 'button' %>
  <% end %>
<% end %>

app/views/student_followings/show.html.erb
<div class="student_followings-show">
  <%= render 'students/nav.html.erb' %>

  <main>
    <div class="followings">
      <h3>フォロー</h3>
      <% @teachers.each do |t| %>
        <% if current_student.already_following?(t)%>
          <div class="user">
            <%= link_to teacher_path(t.id) do %>
              <%= user_icon(t) %>
            <% end %>
            <div class="info">
              <div class="name"><%= t.name %></div> <br>
              <%= render 'student_followings/DM_link', tea: t, ids: @teacher_ids, flwng: current_student.already_following?(t), flwd: current_student.already_followed?(t) %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="followers">
      <h3>フォロワー</h3>
      <% @teachers.each do |t| %>
        <% if current_student.already_followed?(t)%>
          <div class="user">
            <%= link_to teacher_path(t.id) do %>
              <%= user_icon(t) %>
            <% end %>
            <div class="info">
              <div class="name"><%= t.name %></div> <br>
              <%= render 'student_followings/DM_link', tea: t, ids: @teacher_ids, flwng: current_student.already_following?(t), flwd: current_student.already_followed?(t) %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </main>
</div>