config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index' => 'home#index'

  devise_for :students, controllers: {
    sessions:       'students/sessions',
    passwords:      'students/passwords',
    registrations:  'students/registrations'
  }
  resources :students, only: [:index, :show]
  # get 'students/index' => 'students#index'
  # get 'students/show' => 'students#show'


  devise_for :teachers, controllers: {
    sessions:       'teachers/sessions',
    passwords:      'teachers/passwords',
    registrations:  'teachers/registrations'
  }
  resources :teachers, only: [:index, :show]
  # get 'teachers/index' => 'teachers#index'
  # get 'teachers/show' => 'teachers#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :student_followings, only: [:show, :create, :destroy]
  resources :teacher_followings, only: [:show, :create, :destroy]

  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create]
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="home-index">
  <main>
    <% if student_signed_in? %>
      <div class="login-user">
        <%= current_student.name %>としてログインしています
      </div>
      <div class="buttons">
        <%= link_to 'プロフィール詳細', student_path(current_student.id), class: 'button' %>
        <%= link_to 'マッチング画面', students_path, class: 'button' %>
        <%= link_to 'ログアウト', destroy_student_session_path, method: :delete, class: 'button' %>
      </div>
    <% elsif teacher_signed_in? %>
      <div class="login-user">
        <%= current_teacher.name %>としてログインしています
      </div>
      <div class="buttons">
        <%= link_to 'プロフィール詳細', teacher_path(current_teacher.id), class: 'button' %>
        <%= link_to 'マッチング画面', teachers_path, class: 'button' %>
        <%= link_to 'ログアウト', destroy_teacher_session_path, method: :delete, class: 'button' %>
      </div>
    <% else %>
      <div class="buttons">
        <%= link_to '生徒として新規登録', new_student_registration_path, class: 'button' %>
        <%= link_to '先生として新規登録', new_teacher_registration_path, class: 'button' %>
      </div>
    <% end %>
  </main>

  <footer>
    Copyright &copy; Tsuyoshi Nakayama All Rights Reserved.
  </footer>

</div>