config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index' => 'home#index'

  devise_for :students, controllers: {
    sessions:       'students/sessions',
    passwords:      'students/passwords',
    registrations:  'students/registrations'
  }
  resources :students, only: [:index, :show]
  # get 'students/index' => 'students#index'
  # get 'students/show' => 'students#show'


  devise_for :teachers, controllers: {
    sessions:       'teachers/sessions',
    passwords:      'teachers/passwords',
    registrations:  'teachers/registrations'
  }
  resources :teachers, only: [:index, :show]
  # get 'teachers/index' => 'teachers#index'
  # get 'teachers/show' => 'teachers#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :student_followings, only: [:show, :create, :destroy]
  resources :teacher_followings, only: [:show, :create, :destroy]

  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create]
  end


end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  validates :subject, length: { maximum: 100 }

  has_many :student_followings, foreign_key: 'followed_id', dependent: :destroy
  has_many :teacher_followings, foreign_key: 'follow_id', dependent: :destroy
  has_many :followings, through: :teacher_followings, source: :followed
  has_many :followers, through: :student_followings, source: :follow
  has_many :rooms

  mount_uploader :icon, IconUploader

  def follow(student)
    self.teacher_followings.find_or_create_by(followed_id: student.id)
  end

  def unfollow(student)
    relationship = self.teacher_followings.find_by(followed_id: student.id)
    relationship.destroy if relationship
  end

  def already_following?(student)
    self.followings.include?(student)
  end

  def already_followed?(student)
    self.followers.include?(student)
  end

end

app/controllers/teachers/confirmations_controller.rb
# frozen_string_literal: true

class Teachers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/teachers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Teachers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/teachers/passwords_controller.rb
# frozen_string_literal: true

class Teachers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/teachers/registrations_controller.rb
# frozen_string_literal: true

class Teachers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_sign_up_path_for(resource)
    teachers_path(resource)
  end

  def after_update_path_for(resource)
    teacher_path(resource)
  end

end

app/controllers/teachers/sessions_controller.rb
# frozen_string_literal: true

class Teachers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    teachers_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/teachers/unlocks_controller.rb
# frozen_string_literal: true

class Teachers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  before_action :authenticate_teacher!, except: [:show]

  def index
    @teacher = current_teacher
    if params[:search] == nil
      @students = Student.all
    elsif params[:search] == ''
      @students = Student.all
    else
      split_keyword = params[:search].split(/[[:blank:]]+/)
      @students = []
      split_keyword.each do |sk|
        next if sk == ""
        @students += Student.where('name like(?) or profile like(?)', "%#{sk}%","%#{sk}%")
      end
      @students.uniq!
    end
  end

  def show
    @teacher = Teacher.find(params[:id])
    if student_signed_in?
      rooms = current_student.rooms
      @teacher_ids = []
      rooms.each do |r|
        @teacher_ids << r.teacher_id
      end
      @following = current_student.already_following?(@teacher)
      @followed = current_student.already_followed?(@teacher)
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_nav.html.erb
  <nav>
    <div class="my-info">
      <%= link_to teacher_path(current_teacher.id) do %>
        <%= user_icon(current_teacher) %>
      <% end %>
      <div class="name">
        <%= current_teacher.name %>
      </div>
      <div class="detail">
        <div class="subject"><span>担当科目：</span><%= current_teacher.subject %></div>
        <div class="profile"><span>プロフィール：</span><%= current_teacher.profile %></div>
      </div>
    </div>
    <ul class="gnavi">
      <li><%= link_to 'ホーム', root_path %></li>
      <li><%= link_to 'プロフィール', teacher_path(current_teacher.id) %></li>
      <li><%= link_to 'マッチング画面', teachers_path %></li>
      <li><%= link_to 'ログアウト', destroy_teacher_session_path, method: :delete %></li>
    </ul>
    <div class="side-footer">
      Copyright <br>
      &copy; Tsuyoshi Nakayama <br>
      All Rights Reserved.
    </div>
  </nav>

app/views/teachers/index.html.erb
<div class="teachers-index">
  <%= navigation_bar %>

  <main>
    <div class="search-form">
      <%= form_tag({controller:"teachers",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索'  %>
      <% end %>
    </div>
    <h3>生徒一覧</h3>
    <div class="users">
      <% @students.each do |s| %>
        <hr>
        <div class="user">
          <%= link_to student_path(s.id) do %>
            <div class="user-icon"><%= user_icon(s) %></div>
            <div class="info">
              <div class="name"><%= s.name %></div>
              <div class="profile"><span>プロフィール：</span><%= s.profile %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </main>
</div>

app/views/teachers/show.html.erb
<div class="teachers-show">
  <%= navigation_bar %>

  <main>
    <div class="icon-button">
      <%= user_icon(@teacher) %>
      <% if teacher_signed_in? %>
        <div class="buttons">
          <%= link_to '編集', edit_teacher_registration_path, class: 'button' %>
          <%= link_to 'フォロー/フォロワー', teacher_following_path(@teacher.id), class: 'button' %>
        </div>
      <% elsif student_signed_in? %>
        <%= render 'student_followings/follow_button', teacher: @teacher %>
        <br>
        <%= render 'student_followings/DM_link', tea: @teacher, ids: @teacher_ids, flwng: @following, flwd: @followed %>
      <% else %>
        ※ログインしてください。
      <% end %>
    </div>
    <div class="name"><span>名前：</span><%= @teacher.name %></div>
    <div class="subject"><span>担当科目：<br></span><%= @teacher.subject %></div>
    <div class="profile"><span>プロフィール：<br></span><%= @teacher.profile %></div>

  </main>

</div>